jobs:
  backend-test:
    name: Backend Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup and install
        uses: ./.github/actions/setup
        with:
          working-directory: backend

      - name: Run tests
        working-directory: backend
        run: npm test
        env:
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}


  frontend-build:
    name: Frontend Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup and install
        uses: ./.github/actions/setup
        with:
          working-directory: frontend

      - name: Build
        working-directory: frontend
        run: npm run build